---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "{{ site.baseurl }}/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
version: '0.28'
