---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/post
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: content/about.md
  label: About
  match: "**/*"
- type: document
  path: content/code.md
  label: Code of Conduct
  match: "**/*"
upload_dir: static/uploads
public_path: "{{ site.baseurl }}/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
version: '0.28'
